syntax = "proto3";

package Proto;

enum FlightState
{
    FLIGHTSTATE_UNKNOWN = 0;
    UNARMED             = 1;
    GROUNDIDLE          = 2;
    INFLIGHT            = 3;
    MAINCHUTE           = 4;
}

message Control { optional FlightState state = 1; }

message InFlightData
{
    BMP_Data bmp_data            = 1;
    float accel_gyro_temperature = 2;
    VectorF accel                = 3;
    VectorF gyro                 = 4;
    VectorF magnetometer         = 5;
    float thermometer            = 6;
    FlightState flight_state     = 7;
    GPS_Data gps_data            = 8;

    message BMP_Data
    {
        float temperature = 1;
        float pressure    = 2;
        float altitude    = 3;
    }
    message VectorF
    {
        float X = 1;
        float Y = 2;
        float Z = 3;
    }
    message GPS_Data
    {
        float latitude     = 1;
        float longitude    = 2;
        float altitude     = 3;
        float speed        = 4;
        float angle        = 5;
        uint32 fix_quality = 6;
        uint32 satellites  = 7;
    }
}

message SwitchRadioFrequency { float new_frequency = 1; }

message DebugMessage
{
    uint32 status = 1;
    string msg    = 2;
}

message InfoExchange
{
    uint32 radio_version       = 1;
    uint32 proto_3_msg_version = 2;
}

message Ack { uint32 response_to_which_message = 1; }

enum CommandType
{
    COMMAND_UNKNOWN         = 0;
    COMMAND_ABORT           = 1;
    COMMAND_CAMERA_ON       = 2;
    COMMAND_CAMERA_OFF      = 3;
    COMMAND_START_RECORDING = 4;
    COMMAND_STOP_RECORDING  = 5;
    COMMAND_SD_LOG_ON       = 6;
    COMMAND_SD_LOG_OFF      = 7;
}

message CommandMessage
{
    CommandType command = 1;
}

